### PR TITLE
Refactoring for code quality, simplicity, and maintainability

### PR DESCRIPTION
**Pull request by edgrosvenor**
@jlnmay I'm doing some cleanup and simplification of the package in preparation for deploying the production app. Don't merge this because it's not ready. I'll be working on it all weekend and I'll let you know if I have any questions or issues as I go.

### CODE REVIEW

**Comment by jlnmay** [comment]
@edgrosvenor  understood. will wait for that. but I want to ask if I can create another branch, I want to make some improvements in the package as well and before merge it, will create a PR so that you take at look.

**Comment by edgrosvenor** [comment]
@jlnmay Yeah, though I'd prefer not to do a complex 3 way merge. How about I work on it tonight and then hand this branch off to you to do your work on over the weekend. That way you can work from the trimmed down version I'm using. The problem with you creating a fresh branch off main is that I've added some automated code quality checks that have changed basically all the files which means everything would be a conflict.

**Comment by jlnmay** [comment]
@edgrosvenor Yep no problem. I will wait, take your time.

**Comment by edgrosvenor** [comment]
@jlnmay I'm done with what I wanted to do with it. Here's a summary of what I did:

1. I removed the sample app (controllers, Livewire components, views, routes, etc). We'll put together an open source demo app as a separate package later instead of having it embedded in this package.
2. I upgraded the php cs fixer to a version compatible with PHP8.1 and ensured that the package works with 8.1
3. I eliminated all dynamic assignment of properties (fixes a coming breaking change in PHP9)
4. I addressed all errors and warnings discovered via the static analysis provided by PHPStorm's inspectors
5. I removed docblocks, replacing them with return types and parameter types where appropriate. I added back in throws where appropriate to help with future static analysis.
6. I added some attributes to help with static analysis. Primarily pure.
7. I started making notes of seemingly unused classes and methods, but then thought that maybe they're not internally used but are instead used by the app. I'll leave it to you to identify any classes and methods that are, in fact, unused and can be removed.
8. I added a simple assertion to a test that made no assertions, basically just looking for a known string in the value returned from the api.

That's basically it. I hope I didn't break anything too badly. I'll pull this branch into the app tomorrow and see how it all goes. The tests all pass, which is good news. I'm not sure how thorough the test coverage is but we can work on that over time.

The package looks good. This was a much faster process than it usually is. Good work!

**Comment by edgrosvenor** [comment]
Feel free to review this, merge it into main, and then do whatever you had in mind to it. Unless you identify significant issues before then, my plan is to tag version 1.0 on Monday.

**Review by jlnmay — APPROVED** [review]
Looks good to me.

**Comment by jlnmay** [comment]
@edgrosvenor I approved the PR.
1.  What I had in mind it had to do with demo app, but as you mentioned in point 1 that it will be a separate package, I will get back to this later as well.
2. Regarding point 7, the main file for calling FedEx endpoints is FedExController, the other files were created with the idea that others can reuse them (facilitate coding), they are used by fedex-app and if you see they are called between them but they are apart of main file. Will take a look and make notes which files and methods are not used even for fedex-app in order to be removed.

**Pull request merged**
